# Generated by Django 2.2.6 on 2019-11-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='user_profile',
        ),
    ]
