# Generated by Django 2.2.6 on 2019-11-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_remove_productlist_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cat_name', models.CharField(default='DEFAULT VALUE', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='productlist',
            name='product_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.ProductCategory'),
            preserve_default=False,
        ),
    ]
