# Generated by Django 2.2.6 on 2019-11-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20191101_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_cat_name',
            new_name='product_category',
        ),
    ]
